services:
  muses:
    image: happierx/muses
    container_name: muses
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=file:./data/data.db
      - JWT_SECRET=muses-secret
    volumes:
      - ./data:/app/data
      - /your/local/music/path:/app/music
